apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grahamapi-ingress
  namespace: graham-banano
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - grahamapi.banano.cc
    secretName: grahamapi-banano-cc-server-secret
  rules:
  - host: grahamapi.banano.cc
    http:
      paths:
      - path: /
        backend:
          serviceName: graham-banano
          servicePort: 11337