apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bananobot-ingress
  namespace: graham-banano
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - bananobotapi.banano.cc
    secretName: bananobotapi-banano-cc-server-secret
  rules:
  - host: bananobotapi.banano.cc
    http:
      paths:
      - path: /
        backend:
          serviceName: bananobot
          servicePort: 11337