apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nanobotapi-ingress
  namespace: graham-nano
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - nanobotapi.banano.cc
    secretName: nanobotapi-banano-cc-server-secret
  rules:
  - host: nanobotapi.banano.cc
    http:
      paths:
      - path: /
        backend:
          serviceName: graham-nano
          servicePort: 11337